--
-- Paul Moreland
-- pamo18
-- 2019/03/28
--

-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 18:11:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sapo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sapo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sapo` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `sapo` ;

-- -----------------------------------------------------
-- Table `sapo`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sapo`.`person` ;

CREATE TABLE IF NOT EXISTS `sapo`.`person` (
  `id` VARCHAR(10) NOT NULL,
  `fornamn` VARCHAR(45) NULL,
  `efternamn` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapo`.`organisation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sapo`.`organisation` ;

CREATE TABLE IF NOT EXISTS `sapo`.`organisation` (
  `id` VARCHAR(10) NOT NULL,
  `namn` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapo`.`kategori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sapo`.`kategori` ;

CREATE TABLE IF NOT EXISTS `sapo`.`kategori` (
  `typ` VARCHAR(45) NOT NULL,
  `niva` INT NULL,
  PRIMARY KEY (`typ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sapo`.`logg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sapo`.`logg` ;

CREATE TABLE IF NOT EXISTS `sapo`.`logg` (
  `id` INT NOT NULL,
  `kategori_typ` VARCHAR(45) NULL,
  `person_id` VARCHAR(10) NULL,
  `organisation_id` VARCHAR(10) NULL,
  `vad` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `person_id_log_idx` (`person_id` ASC) VISIBLE,
  INDEX `org_id_log_idx` (`organisation_id` ASC) VISIBLE,
  CONSTRAINT `person_id_log`
    FOREIGN KEY (`person_id`)
    REFERENCES `sapo`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `org_id_log`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `sapo`.`organisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kat_typ_log`
    FOREIGN KEY (`kategori_typ`)
    REFERENCES `sapo`.`kategori` (`typ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
