-- MySQL Script generated by MySQL Workbench
-- Tue Mar 26 19:14:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exam
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exam` DEFAULT CHARACTER SET utf8 COLLATE utf8_swedish_ci ;
USE `exam` ;

-- -----------------------------------------------------
-- Table `exam`.`sushi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exam`.`sushi` ;

CREATE TABLE IF NOT EXISTS `exam`.`sushi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `details` TEXT NULL,
  `sushi_date` TIMESTAMP NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `produkt_namn_index` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exam`.`competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exam`.`competition` ;

CREATE TABLE IF NOT EXISTS `exam`.`competition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `details` TEXT NULL,
  `comp_date` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exam`.`sushi2competition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `exam`.`sushi2competition` ;

CREATE TABLE IF NOT EXISTS `exam`.`sushi2competition` (
  `competition_id` INT NOT NULL,
  `sushi_id` INT NOT NULL,
  `vote` INT NULL DEFAULT 0,
  INDEX `t2_id_idx` (`competition_id` ASC) VISIBLE,
  INDEX `t1_id_idx` (`sushi_id` ASC) VISIBLE,
  CONSTRAINT `t2_id`
    FOREIGN KEY (`competition_id`)
    REFERENCES `exam`.`competition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `t1_id`
    FOREIGN KEY (`sushi_id`)
    REFERENCES `exam`.`sushi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
