-- MySQL Script generated by MySQL Workbench
-- Mon Mar 18 14:21:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `eshop`.`produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`produkt` ;

CREATE TABLE IF NOT EXISTS `eshop`.`produkt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `namn` VARCHAR(45) NOT NULL,
  `pris` DECIMAL(18,2) NOT NULL,
  `bild_lank` VARCHAR(45) NULL,
  `beskrivning` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `produkt_namn_index` (`namn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`kategori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`kategori` ;

CREATE TABLE IF NOT EXISTS `eshop`.`kategori` (
  `typ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`typ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`kund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`kund` ;

CREATE TABLE IF NOT EXISTS `eshop`.`kund` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fornamn` VARCHAR(45) NOT NULL,
  `efternamn` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL,
  `postnummer` VARCHAR(45) NULL,
  `ort` VARCHAR(45) NULL,
  `land` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `kund_fornamn_index` (`fornamn` ASC) VISIBLE,
  INDEX `kund_efternamn_index` (`efternamn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`orders` ;

CREATE TABLE IF NOT EXISTS `eshop`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kund_id` INT NULL,
  `order_status` VARCHAR(45) NULL,
  `order_created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `order_updated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `order_placed` TIMESTAMP NULL DEFAULT NULL,
  `order_sent` TIMESTAMP NULL DEFAULT NULL,
  `order_deleted` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `kund_id_idx` (`kund_id` ASC) VISIBLE,
  CONSTRAINT `kund_id_order`
    FOREIGN KEY (`kund_id`)
    REFERENCES `eshop`.`kund` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`lager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`lager` ;

CREATE TABLE IF NOT EXISTS `eshop`.`lager` (
  `hylla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hylla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`logg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`logg` ;

CREATE TABLE IF NOT EXISTS `eshop`.`logg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tid` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `handelse` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`order2produkt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`order2produkt` ;

CREATE TABLE IF NOT EXISTS `eshop`.`order2produkt` (
  `order_id` INT NOT NULL,
  `produkt_id` INT NOT NULL,
  `kvantitet` INT NOT NULL,
  INDEX `produkt_id_idx` (`produkt_id` ASC) VISIBLE,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `produkt_id_op`
    FOREIGN KEY (`produkt_id`)
    REFERENCES `eshop`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_id_op`
    FOREIGN KEY (`order_id`)
    REFERENCES `eshop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`produkt2kategori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`produkt2kategori` ;

CREATE TABLE IF NOT EXISTS `eshop`.`produkt2kategori` (
  `produkt_id_kat` INT NOT NULL,
  `kategori` VARCHAR(45) NOT NULL,
  INDEX `produkt_id_pkat_idx` (`produkt_id_kat` ASC) VISIBLE,
  INDEX `kategori_typ_pkat_idx` (`kategori` ASC) VISIBLE,
  CONSTRAINT `produkt_id_pkat`
    FOREIGN KEY (`produkt_id_kat`)
    REFERENCES `eshop`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `kategori_pkat`
    FOREIGN KEY (`kategori`)
    REFERENCES `eshop`.`kategori` (`typ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`produkt2lager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`produkt2lager` ;

CREATE TABLE IF NOT EXISTS `eshop`.`produkt2lager` (
  `produkt_id_lag` INT NOT NULL,
  `antal` INT NULL,
  `hylla_id` VARCHAR(45) NOT NULL,
  INDEX `produkt_id_lager_idx` (`produkt_id_lag` ASC) VISIBLE,
  INDEX `hylla_id_lager_idx` (`hylla_id` ASC) VISIBLE,
  CONSTRAINT `produkt_id_lager`
    FOREIGN KEY (`produkt_id_lag`)
    REFERENCES `eshop`.`produkt` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hylla_id_lager`
    FOREIGN KEY (`hylla_id`)
    REFERENCES `eshop`.`lager` (`hylla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`faktura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`faktura` ;

CREATE TABLE IF NOT EXISTS `eshop`.`faktura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sent` TIMESTAMP NOT NULL,
  `kund_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT 'Ej betald',
  `paid` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `kund_id_fak_idx` (`kund_id` ASC) VISIBLE,
  INDEX `order_id_fak_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `kund_id_fak`
    FOREIGN KEY (`kund_id`)
    REFERENCES `eshop`.`kund` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_id_fak`
    FOREIGN KEY (`order_id`)
    REFERENCES `eshop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eshop`.`spec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eshop`.`spec` ;

CREATE TABLE IF NOT EXISTS `eshop`.`spec` (
  `faktura_id` INT NOT NULL,
  `produkt_namn` VARCHAR(45) NULL,
  `antal` INT NULL,
  `pris` DECIMAL(18,2) NULL,
  INDEX `faktura_id_idx` (`faktura_id` ASC) VISIBLE,
  CONSTRAINT `faktura_id`
    FOREIGN KEY (`faktura_id`)
    REFERENCES `eshop`.`faktura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
